### ISSUE TITLE
LICENSING

### ISSUE THREAD

**Issue by Tsutsukakushi** [gnubee-git/GnuBee_Docs#1]
Your license currently only says "NONE". This makes the project proprietary, the crowdsupply was listed on open hardware despite the license not reflecting that. I would recommend adding a license in case it is actually meant to be open hardware and not closed.

**Comment by pinney** [comment]
Documentation Content created by GnuBee is licensed under the following license : CC-BY-SA
http://creativecommons.org/licenses/by-sa/4.0/


Look OK?

**Comment by Tsutsukakushi** [comment]
That's OK :)

**Comment by Tsutsukakushi** [comment]
Should still replace the LICENSE file with it in the repo

**Comment by pinney** [comment]
I'll push it later....CC-BY-SA is only for the Documents the software is still GPL or more permissive
