### ISSUE TITLE
Local ip address changes on every reboot.

### ISSUE THREAD

**Issue by Qwertie-** [gnubee-git/GnuBee_Docs#103]
This seems like a bit of a strange issue and I'm not sure the gnubee is at fault but no other devices on my network seem to do this. Every time the gnu bee reboots it gets a new local IP address. My routers device page shows a new listing for the gnu bee added every time it boots. Has anyone else had this issue?

**Comment by xvybihal** [comment]
Just a wild guess. Do you have same MAC or it also always change? 
I think I had this long time ago. What kernel you using?

**Comment by Qwertie-** [comment]
Kernel is `Linux gnubee.gnubee 4.4.172 #5 SMP Mon Feb 4 07:45:13 UTC 2019 mips GNU/Linux` using the Neil brown build. I'll have to keep an eye on the mac address. Thats probably what's tripping up my router.

**Comment by Qwertie-** [comment]
Yeah I can see the mac address changes on every reboot

**Comment by neheb** [comment]
probably need new firmware. mac address can be edited in the bootloader menu.

**Comment by Qwertie-** [comment]
@neheb Is there any way to update it or do I have to reinstall?

**Comment by Qwertie-** [comment]
This was fixed after installing the 5.2 firmware
