### ISSUE TITLE
GPIO usage with Linux

### ISSUE THREAD

**Issue by Adirelle** [gnubee-git/GnuBee_Docs#25]
I may have overlooked something. But are the GPIO on the J4 header already used for something ?

The same question goes for GPIO18 (push button): is it already used somehow (using the linux device tree maybe) ?

**Comment by pinney** [comment]
GPIO @ J4 
These GPIOs are available for the user.
GPIO 26, 28, 29 and 30
Shown on page 13 
https://github.com/gnubee-git/GnuBee_Docs/blob/master/GB-PC1/Documents/GB-PC1_V1.0_Schematic.pdf

Reset Key from GB-PC1.dts : 
	gpio-keys-polled {
		compatible = "gpio-keys-polled";
		#address-cells = <1>;
		#size-cells = <0>;
		poll-interval = <20>;

		reset {
			label = "reset";
			gpios = <&gpio0 18 GPIO_ACTIVE_HIGH>;
			linux,code = <KEY_RESTART>;
		};
	};

**Comment by Adirelle** [comment]
Thanks for the quick reply.
