### ISSUE TITLE
Access Issue

### ISSUE THREAD

**Issue by bcupps** [gnubee-git/GnuBee_Docs#26]
When I first received the unit and put it together, I was able to access the system but when I updated the network address, set password, etc... the changes weren't saved after a restart. Tonight, I flashed the Debian firmware as per the instructions but now I can't access the system at all. I've tried the 192.168.10.1 address as well as scanned for systems on the entire subnet. Thoughts as to what's going on and how I can access it?

**Comment by pinney** [comment]
libreCMC is on 192.168.10.1
LEDE-project uses 192.168.1.1
Please try 192.168.1.1
