### ISSUE TITLE
How to return a failed board for exchange?

### ISSUE THREAD

**Issue by vmmello** [gnubee-git/GnuBee_Docs#42]
Hi,

I purchased a PC1 board on pre-order. My board worked well for about 1 hour and then froze (was on full metal assembly, no manipulating of it meanwhile it was turned on). After that it hangs on boot, generally before showing the U-Boot menu. And when it boots (what is rare) it ends up with a kernel panic on a different point every time. I tried updating the libreCMC firmware with a USB stick but it also hangs a few seconds after starting.

I didn't find any page instructing how to deal with exchanging of failed boards, though on some other issues here on Github there's the mention to send it directly to Crowdsupply.

Should I send it to Crowdsupply as instructed on their [page of backer protection](https://www.crowdsupply.com/guide/backer-protection#terms-and-policies-return-refund-cancellation)?
```
Should any item fail to meet your expectations, simply return the item in new condition and we will 
gladly exchange it, refund your purchase price with a store credit, or credit your credit card. If you’re 
not sure a product is going to work for you, we ask you please keep all packing materials for shipping,
should you decide to return it. No return authorization number is necessary. Just ship your items back
to us with a copy of your invoice or a printout of your confirmation email and a note indicating how 
you’d like us to handle the return (refund or exchange). Please include your daytime phone number in 
case we have any questions.
```

It'd be good if there was a page on the website instructing how to proceed with the exchange of failed boards.

Thanks in advance.

**Comment by pinney** [comment]
@vmmello 

Please contact Crowd Supply for a return.

Thanks!
