### ISSUE TITLE
Include build configs

### ISSUE THREAD

**Issue by singron** [gnubee-git/GnuBee_Docs#43]
How are you configuring the builds? Could you commit the config you used for each image, and maybe a [diffconfig](https://lede-project.org/docs/guide-developer/use-buildsystem#configure_using_config_diff_file) as well. Thanks.

**Comment by dgazineu** [comment]
Here at https://github.com/gnubee-git/gnubee-openwrt/ , the file is GB-Deb.config , and at https://github.com/gnubee-git/GnuBee-lede/tree/lede-17.01 (note the branch) the file is GB-PC1_defconfig
