### ISSUE TITLE
Hard system freeze with samba

### ISSUE THREAD

**Issue by optlink** [gnubee-git/GnuBee_Docs#45]
I have been having this issue for quite a while now and it is seriously impacting my use case for this device. My setup is this:

GnuBee running latest LEDE image
Raspberry Pi 2 running LibreELEC 8.2.0.1
Laptop running Arch Linux
Server running Arch Linux

The GnuBee is running 6 drives in a RAID 1 array using btrfs. There is a public readonly share hosted with samba. All the other devices are transferring data to and from the GnuBee using only SMB2. 

The problem is that the Raspberry Pi will somehow cause the GnuBee to totally lockup randomly when playing a video. It can happen up to four times in a single movie or only once in two days with no apparent pattern. The laptop and server can copy data with no issues but doing so concurrently with the Raspberry Pi appears to increase the frequency of these lockups, though I can't say for certain.

I read somewhere that Kodi calls into libsmb directly as opposed to using the CIFS driver provided by the kernel so I set up a systemd automount and the problem still occurs.

Some additional information that may be related:
The GnuBee is configured to act as a switch. So the network layout looks like this: Pi --> GnuBee --> Router
The idea is that the GnuBee and the Raspberry Pi both get their IP addresses from the router and the Pi is transparently accessible to the rest of my network.

Anyone else having this problem or something like it?

**Comment by optlink** [comment]
In search of a workaround I managed to get some success by essentially proxying through another samba server. However, I discovered that the GnuBee hangs under heavy read traffic. Writes seem to be perfectly fine. I don't know if this is a samba or btrfs issue and it's pretty difficult to check without being able to install nfs (can't satisfy dependencies?) and I cannot get minidlna to do anything other than waste resources.

**Comment by optlink** [comment]
Well it looks like setting "use sendfile = no" in the samba template has solved the problem. I think this default should really be changed.

**Comment by Adirelle** [comment]
Hello, 

I am curious: which branch of the GnuBee LEDE repository are you using ? Some settings (like nfs and acl support) are disabled by default. Are you using the version of minidlna provided with it ?

**Comment by optlink** [comment]
@Adirelle I'm not sure which branch I'm using. I flashed the firmware found here: https://github.com/gnubee-git/GnuBee_Docs/tree/master/GB-PC1/firmware/GnuBee-LEDE-17.01

As far as I know, minidlna and the nfs server tools are not included with this build and must be installed through opkg. Here is the firmware version displayed in luci if it helps: 
LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.298.45605-07e7ff0)

**Comment by neheb** [comment]
@optlink with trunk builds, you usually need to recompile the whole image. With stable images, the kmods in the repository are enough. You could try opkg install X --force-depends to force install NFS or whatever, which sometimes works.

Easiest way is to just recompile.

That sendfile = no thing is interesting. sendfile is a kernel thing. That;s weird that it's causing issues, although I've experienced something similar when seeking through videos. I'll look to see what the performance impact of disabling it is.

**Comment by optlink** [comment]
@neheb The only reason I was messing with NFS and minidlna was to see if it was samba causing the hangs. Now that I have the system working farily well it doesn't bother me if I can't install them.

Regarding performance it could just be that my btrfs array isn't fast enough to hit the limit but I am getting speeds more than fast enough for my usecase. Actually, the setting most detrimental to performance was having SMB1 enabled. I could barely reach 5MB/sec when that was on, though I think that was due to a client limitation which was lifted around the same time I was debugging this issue.

I still get hangs roughly every 10 days, under load or not, but I think these are caused by something else because when they happen the front LEDs are completely off. The samba hangs would have at least one LED still on and only occur when reading from a share. I really have no idea where to begin searching with this one but they are infrequent enough that I am able to live with it for now.

**Comment by neheb** [comment]
Weird, mounting with -o vers=1.0 is faster for me.

When the hangs occur, does the whole system lock up? I've actually had the
Ethernet driver die on me before. It didn't lock up the whole system but I
verified through a serial console that it died.

**Comment by optlink** [comment]
@neheb I don't have the serial cable.

**Comment by neheb** [comment]
could try logging to a file. it should write the error.

**Comment by optlink** [comment]
Last time I tried that there was nothing. I've set it up again anyway and we'll see what happens. Also, the system time is off by about 15 minutes after about 40 hours of uptime.

**Comment by neheb** [comment]
That system time issue requires new firmware. Or flashing your U-boot to
880Mhz. The drift happens because the firmware thinks it's running at
880Mhz and the clock ends up running too fast.

**Comment by dgazineu** [comment]
Updated firmware:
https://github.com/gnubee-git/gnubee-git.github.io/raw/master/debian/librecmc-ramips-mt7621-gb-pc1-squashfs-sysupgrade_2017-11-28.bin
Sha256sum: e2fe4cd4f70dc04372d5a7dcf1443d6895cd3e797a65c1d9ec889d79db181493

Changes: Fixed clock skew

Installation instructions @ http://gnubee.org/install_debian.html
Sources are available @ https://gogs.librecmc.org/dgazineu/GnuBee-libreCMC

**Comment by Adirelle** [comment]
@nehub How do you check the Ethernet driver died ? Is it possible to "restart" it without rebooting ?

**Comment by neheb** [comment]
@Adirelle i used serial and dmesg. No idea if it can be restarted without rebooting.

**Comment by m3744** [comment]
I have same problem, look 1080p video(streaming to my laptop)45 mb/s, random time nas will become to freeze status

**Comment by neheb** [comment]
@m3744 set send file = no in the samba configuration

**Comment by m3744** [comment]
it's work !!, I play  complete 60 min 1080p video, system status is nornal, not have this problem happen, thanks

**Comment by cmm** [comment]
Huh.  So my PC2 started serving a lot of 1080p videos recently, not over Samba though but NFS.  That made it lock up randomly within an hour -- that is, the serial console is alive, the currently-served media file is usually (not always) served till the end, but otherwise PC2's ethernet connection is completely MIA, so the PC2 is alive but deaf and dumb.  And nothing relevant in the console log, BTW.

The previous usage pattern of mostly-720p over NFS was OK, so definitely something to do with amount of traffic at least.

(Moved to Samba with sendfile = no, will see how that fares...)

**Comment by xvybihal** [comment]
I have very similar experience as you @cmm - yesterday I was watching 1080p movie, it froze 2 times within hour. When watching 720p, it's mostly okay - freezes just like once a week. The GnuBee itself is running, just not accessible over network. The netowrk adaper diod is blinking.
Sorry I do not have other hard data and logs, just wanted to let @cmm he is not alone. I have GB1 btw.

**Comment by cmm** [comment]
@xvybihal, thanks for the moral support :)

On a tangent: for a while some months ago I tried to use NFS shares on the media player (i.e. client side) using normal Linux mounts (i.e. not through Kodi, which uses a user-space NFS client library).  That made the player freeze up randomly. The player is an ARM-based originally-Android box, now running LibreElec.

So, based on this hugely representative sample of 2 devices, I am willing to make the sweeping claim that the Linux VFS/network interplay is not something your typical SoC vendor cares about (and why would they, when the SoCs in question are made for Android boxes or routers), to whatever extent it works at all it does by lucky accident, and so you better stick to streaming bytes over user-space sockets and don't try to get fancy.
