### ISSUE TITLE
SATA controller instability on kernel 4.9

### ISSUE THREAD

**Issue by neheb** [gnubee-git/GnuBee_Docs#48]
I've been having issues with the GnuBee for a really long time and have recently narrowed it down to kernel 4.9 (i run trunk LEDE with my own changes). Has anyone else encountered this? With btrfs I constantly get errors like:

BTRFS warning (device sdc): sdc checksum verify failed on 819822592 wanted 457A99DD found 1606499D level 0

Which slots are used does not seem to matter. On mdadm + ext4 (which does not protect against silent data corruption), data gets wrecked fast. For example, after 3 days uptime, a torrent that used to verify at 100% verifies at 97.x%. After rebooting the router(hard or soft), it goes back to 100%. On btrfs it tries to keep it at 100 but usually goes down to 99.x%.

I've recently started using kernel 4.4 for my builds and have not noticed any issues.  Just wondering if anyone has a similar experience.

**Comment by dgazineu** [comment]
Kernel 4.9 is still not recommended for GB boards. We are under testing, but several problems are still present.
The most up-to-date firmware is @ http://gnubee.org/install_debian.html (https://github.com/gnubee-git/gnubee-git.github.io/raw/master/debian/librecmc-ramips-mt7621-gb-pc1-squashfs-sysupgrade_2017-11-28.bin)
If you want to fiddle with it, the sources are available @ https://gogs.librecmc.org/dgazineu/GnuBee-libreCMC
