### ISSUE TITLE
libreCMC feed address incorrect, can't update lists

### ISSUE THREAD

**Issue by sluzynsk** [gnubee-git/GnuBee_Docs#5]
The core directory changed to:

src/gz frivolous_fred_core https://librecmc.org/librecmc/downloads/snapshots/v1.4-core/ramips/mt7621/packages

the default install still points at v1.4/, not v1.4-core/.

**Comment by pinney** [comment]
Were you able to fix that in your configuration?
What firmware do you have installed?
The shipped version or the recently updated one?

**Comment by sluzynsk** [comment]
Yes, I had no trouble fixing it - this is more to let you know that it was needing fixed moving forward. It was in the firmware released a day or two ago, I only ran the shipping firmware long enough to update it. :)

**Comment by pinney** [comment]
Thanks! 
Closing
