### ISSUE TITLE
Sugested Modification to PC-2 Side plates for mounting 2.5" drives

### ISSUE THREAD

**Issue by hvontres** [gnubee-git/GnuBee_Docs#69]
I just created a quick sketch of a modified version of the PC-2 Side plate that also has mounting holes for 2.5" drives. This would allow one side of the drive to be mounted to the side plate, since the distance from the connector to the drive edge on the left side (as viewed from the power switch) is the same for both sizes, according to the sata standard.

[pc2_mod.pdf](https://github.com/gnubee-git/GnuBee_Docs/files/1779967/pc2_mod.pdf)

**Comment by pinney** [comment]
@hvontres 

Thanks ... just pushed this up : 
GB-PCx/Documents/PC2_Side_Plate_Mod.pdf
