### ISSUE TITLE
Rset root password

### ISSUE THREAD

**Issue by stijnhau** [gnubee-git/GnuBee_Docs#74]
Had issues setting up so ordered an sd card with debian preinstalled.
Wanting to configure it and it doesn't accept an emty paswoord.

Is there a hardware reset button?
There is aslo no webinterface shown.

**Comment by sumpfralle** [comment]
Maybe `GnuBee` is the proper word?

See http://gnubee.org/install_debian.html

**Comment by neilbrown** [comment]
I think this has been suitably answered, so I'm closing it - thanks.
