### ISSUE TITLE
Proposal for a GnuBee home page

### ISSUE THREAD

**Issue by ngiger** [gnubee-git/GnuBee_Docs#8]
As I would like to have a similar informative page for the GnuBee PC as Martin Michlmayers page on installling Debian on a QNAP device (see http://www.cyrius.com/debian/kirkwood/qnap/ts-119/), I added a gh-pages branch in my repository https://github.com/ngiger/GnuBee_Docs/tree/gh-pages. The result is shown under

https://github.com/gnubee-git/GnuBee_Docs

Feell free to submit suggestion for imrovements/corrections. If you want to add it to your repository the following steps should work
  
    git remote add ngiger https://github.com/ngiger/GnuBee_Docs.git
    git fetch ngiger
    git checkout gh-pages

https://help.github.com/articles/using-a-custom-domain-with-github-pages/ documents how it would be easy to use the web page under another domain name (eg. gnubee.org).

There are some word on how to setup a webserver to test changes in the readme.txt.

The whole pages is inspired by a project a work with (http://elexis.info), where I copied a lot of ideas from https://buildr.apache.org/

**Comment by pinney** [comment]
@ngiger  When it comes to web pages ... I get lost easily :)
I would say go right ahead ... I'm happy to have help.

**Comment by FHulot** [comment]
This is great, ngiger. Thank you.

**Comment by Honos2014** [comment]
It would be great, indeed.

**Comment by ngiger** [comment]
http://gnubee.org/ is up and running and documents firmware and debian installation.
