### ISSUE TITLE
 `ethtool` gives wrong information

### ISSUE THREAD

**Issue by nariox** [gnubee-git/GnuBee_Docs#85]
Hello,
I'm running Neil Brown's 4.4.144 kernel and debian buster. For some reason running`ethtool  eth0` gives me
```
...
        Speed: 10Mb/s
        Duplex: Half
...
```
Is this a bug with ethtool? I'm clearly getting gigabit speeds (confirmed by `iperf` and `netperf`). But it still feels odd to me that ethtool would give the wrong values.

**Comment by neilbrown** [comment]
The ethtool support in the ethernet drives is ... limited.  One might even say "non existant".

**Comment by nariox** [comment]
I see. Thanks for letting me know. I was hoping that would give me some hints on some performance bottlenecks I'm having, but I'll open a new issue for that.
