### ISSUE TITLE
Failed to encrypt home folders in debian because of missing module ecryptfs

### ISSUE THREAD

**Issue by DurtalDeepDown** [gnubee-git/GnuBee_Docs#88]
Heiho, 

I installed libreCMC on my GnuBee PC1 and Debian Jessie on top of it. I also updated to Stretch. Since I am not the only user on it, I want to encrypt the home folders for every user. I have to admit that I don’t know anything about encryption. After some research I tried ecryptfs. This gives: 

`ERROR: Cannot get ecryptfs version, ecryptfs kernel module not loaded? `

The module seems to be absent. So I tried to build the libreCMC firmware including it but could not find a corresponding entry in the build-menu. I am afraid this might be impossible because https://elrepo.org/tiki/kmod-ecryptfs says that ecryptfs is not available for mipsel. 

Am I correct that this leads to nowhere? That I wont be able to use ecryptfs on the GnuBee? And if so, does anyone have another suggestion how to conveniently secure data in your home folder that is so sensible that not even root should be allowed to see it?

**Comment by abesnier** [comment]
It's an old comment, but indeed, the package ecryptfs-utils is not available anymore for jessie/mipsel. You can try to update to Stretch (the wiki can assist you), or you can try to change your `etc/apt/sources.list` and replace  http://httpredir.debian.org/debian by http://archive.debian.org/debian/. The package may be available in the archive folders.
