### ISSUE TITLE
Error in debian-install-script

### ISSUE THREAD

**Issue by DurtalDeepDown** [gnubee-git/GnuBee_Docs#89]
Hello,

during a recent reinstall I noticed that the install script https://raw.githubusercontent.com/gnubee-git/GnuBee_Docs/master/GB-PCx/scripts/jessie_3.10.14/debian-jessie-install isn’t working properly. To fix it, line 62 has to be altered: “debian_fix ${1}” instead of “debian_fix”. This will avoid problems on line 47.

**Comment by fmarier** [comment]
Fixed in 24a0fec9199bc84ea2b77e27aca26c6cdb6614c7.
